#!/usr/bin/env bash
# ============================================================
# modules/cert.sh
# Cloudflare DNS 证书申请模块（已修复）
# ============================================================

CF_CONFIG_DIR="/etc/cloudflare"
CF_DOMAIN_MAP_FILE="${CF_CONFIG_DIR}/domain_map.conf"
CF_CERT_STATUS_FILE="${CF_CONFIG_DIR}/cert_request_status.conf"

# 证书统一存放目录（供 Xray / Nginx / Sing-Box 读取）

# ── 检测 Certbot 是否已安装 ──────────────────────────────────
check_certbot_installed() {
    if command -v certbot &>/dev/null; then
        log_info "Certbot 已安装: $(certbot --version 2>&1)"
        return 0
    fi
    return 1
}

# ── 判断是否使用 Snap 安装的 Certbot ─────────────────────────
certbot_uses_snap() {
    command -v snap &>/dev/null && snap list certbot >/dev/null 2>&1
}

# ── 安装并启用 snapd ─────────────────────────────────────────
install_snapd() {
    log_step "安装 snapd..."

    case "$OS_ID" in
        ubuntu|debian)
            $PKG_INSTALL snapd -y >/dev/null 2>&1
            ;;
        centos|rhel|rocky|almalinux|fedora)
            $PKG_INSTALL epel-release -y >/dev/null 2>&1 || true
            $PKG_INSTALL snapd -y >/dev/null 2>&1
            ;;
        *)
            return 1
            ;;
    esac

    systemctl enable --now snapd.socket >/dev/null 2>&1
    systemctl enable --now snapd.seeded.service >/dev/null 2>&1 || true
    [[ -e /snap ]] || ln -s /var/lib/snapd/snap /snap

    for _ in {1..10}; do
        if command -v snap &>/dev/null; then
            return 0
        fi
        sleep 1
    done

    return 1
}

# ── 移除旧版 Certbot 包 ─────────────────────────────────────
remove_legacy_certbot() {
    case "$OS_ID" in
        ubuntu|debian)
            apt-get remove -y certbot python3-certbot-dns-cloudflare \
                >/dev/null 2>&1 || true
            ;;
        centos|rhel|rocky|almalinux|fedora)
            dnf remove -y certbot python3-certbot-dns-cloudflare \
                >/dev/null 2>&1 || true
            yum remove -y certbot python3-certbot-dns-cloudflare \
                >/dev/null 2>&1 || true
            ;;
    esac
}

# ── 使用 Snap 安装 Certbot + CF 插件 ────────────────────────
install_certbot_snap() {
    install_snapd || return 1

    log_step "使用 Snap 安装最新 Certbot..."
    remove_legacy_certbot

    snap install core >/dev/null 2>&1 || true
    snap refresh core >/dev/null 2>&1 || true
    snap install --classic certbot >/dev/null 2>&1 || \
        snap refresh certbot >/dev/null 2>&1
    snap set certbot trust-plugin-with-root=ok >/dev/null 2>&1 || true
    snap install certbot-dns-cloudflare >/dev/null 2>&1 || \
        snap refresh certbot-dns-cloudflare >/dev/null 2>&1

    ln -sfn /snap/bin/certbot /usr/local/bin/certbot
    command -v certbot &>/dev/null
}

# ── 旧方案回退安装 ───────────────────────────────────────────
install_certbot_legacy() {
    log_warn "Snap 安装失败，回退到系统/PIP 方式安装 Certbot"

    case "$OS_ID" in
        ubuntu|debian)
            $PKG_INSTALL python3-pip python3-venv -y >/dev/null 2>&1
            pip3 install certbot certbot-dns-cloudflare \
                --break-system-packages >/dev/null 2>&1 || \
            pip3 install certbot certbot-dns-cloudflare >/dev/null 2>&1
            ;;
        centos|rhel|rocky|almalinux|fedora)
            $PKG_INSTALL python3-pip -y >/dev/null 2>&1
            pip3 install certbot certbot-dns-cloudflare \
                >/dev/null 2>&1 || \
            $PKG_INSTALL certbot python3-certbot-dns-cloudflare \
                -y >/dev/null 2>&1
            ;;
    esac
}

# ── 安装 Certbot + CF 插件 ───────────────────────────────────
install_certbot() {
    if check_certbot_installed; then
        read -rp "Certbot 已安装，是否重新安装？[y/N]: " reinstall
        [[ "${reinstall,,}" != "y" ]] && return
    fi

    log_step "安装 Certbot + Cloudflare 插件..."

    if ! install_certbot_snap; then
        install_certbot_legacy
    fi

    if ! command -v certbot &>/dev/null; then
        log_error "Certbot 安装失败"
        exit 1
    fi

    log_info "Certbot 安装完成: $(certbot --version 2>&1)"
    if certbot_uses_snap; then
        log_info "当前使用 Snap 版 Certbot（官方推荐）"
    else
        log_warn "当前未使用 Snap 版 Certbot，后续仍可能受系统 Python 版本影响"
    fi
}

# ── 保存域名配置 ─────────────────────────────────────────────
save_domain_config() {
    mkdir -p "$CF_CONFIG_DIR"
    chmod 700 "$CF_CONFIG_DIR"

    {
        echo "# Auto-generated by xray-nginx-deploy cert module"
        echo "CF_ACCOUNT_COUNT='${CF_ACCOUNT_COUNT:-1}'"
        echo "XHTTP_DOMAIN='${XHTTP_DOMAIN:-}'"
        echo "GRPC_DOMAIN='${GRPC_DOMAIN:-}'"
        echo "REALITY_DOMAIN='${REALITY_DOMAIN:-}'"
        echo "ANYTLS_DOMAIN='${ANYTLS_DOMAIN:-}'"
        declare -p ALL_DOMAINS       2>/dev/null || echo "declare -a ALL_DOMAINS=()"
        declare -p CDN_DOMAINS       2>/dev/null || echo "declare -a CDN_DOMAINS=()"
        declare -p DIRECT_DOMAINS    2>/dev/null || echo "declare -a DIRECT_DOMAINS=()"
        declare -p DOMAIN_CF_ACCOUNT_KEYS 2>/dev/null || \
            echo "declare -a DOMAIN_CF_ACCOUNT_KEYS=()"
        declare -p DOMAIN_CF_ACCOUNT_VALS 2>/dev/null || \
            echo "declare -a DOMAIN_CF_ACCOUNT_VALS=()"
        # FIX Bug5: 同时保存 CF_INI_FILES，避免下次加载后为空
        declare -p CF_INI_FILES 2>/dev/null || echo "declare -a CF_INI_FILES=()"
    } > "$CF_DOMAIN_MAP_FILE"

    chmod 600 "$CF_DOMAIN_MAP_FILE"
}

# ── 加载域名配置 ─────────────────────────────────────────────
load_domain_config() {
    [[ -f "$CF_DOMAIN_MAP_FILE" ]] || return 1
    # shellcheck source=/dev/null
    source "$CF_DOMAIN_MAP_FILE"
    # 加载后重建 CF_INI_FILES（兼容旧版配置文件没有该字段的情况）
    if [[ ${#CF_INI_FILES[@]} -eq 0 ]]; then
        rebuild_cf_ini_files
    fi
    if [[ ${#ALL_DOMAINS[@]} -eq 0 ]]; then
        [[ -n "${XHTTP_DOMAIN:-}"   ]] && ALL_DOMAINS+=("$XHTTP_DOMAIN")   && CDN_DOMAINS+=("$XHTTP_DOMAIN")
        [[ -n "${GRPC_DOMAIN:-}"    ]] && ALL_DOMAINS+=("$GRPC_DOMAIN")    && CDN_DOMAINS+=("$GRPC_DOMAIN")
        [[ -n "${REALITY_DOMAIN:-}" ]] && ALL_DOMAINS+=("$REALITY_DOMAIN") && DIRECT_DOMAINS+=("$REALITY_DOMAIN")
        [[ -n "${ANYTLS_DOMAIN:-}"  ]] && ALL_DOMAINS+=("$ANYTLS_DOMAIN")  && DIRECT_DOMAINS+=("$ANYTLS_DOMAIN")
    fi
    return 0
}

normalize_domain_arrays() {
    local normalized_all=()
    local normalized_cdn=()
    local normalized_direct=()

    [[ -n "${XHTTP_DOMAIN:-}"   ]] && normalized_all+=("$XHTTP_DOMAIN")   && normalized_cdn+=("$XHTTP_DOMAIN")
    [[ -n "${GRPC_DOMAIN:-}"    ]] && normalized_all+=("$GRPC_DOMAIN")    && normalized_cdn+=("$GRPC_DOMAIN")
    [[ -n "${REALITY_DOMAIN:-}" ]] && normalized_all+=("$REALITY_DOMAIN") && normalized_direct+=("$REALITY_DOMAIN")
    [[ -n "${ANYTLS_DOMAIN:-}"  ]] && normalized_all+=("$ANYTLS_DOMAIN")  && normalized_direct+=("$ANYTLS_DOMAIN")

    if [[ ${#normalized_all[@]} -gt 0 ]]; then
        ALL_DOMAINS=("${normalized_all[@]}")
        CDN_DOMAINS=("${normalized_cdn[@]}")
        DIRECT_DOMAINS=("${normalized_direct[@]}")
    fi
}

# ── 保存证书请求状态 ─────────────────────────────────────────
save_cert_request_status() {
    mkdir -p "$CF_CONFIG_DIR"
    chmod 700 "$CF_CONFIG_DIR"

    {
        echo "# Auto-generated by xray-nginx-deploy cert module"
        declare -p CERT_SUCCESS_ROOTS  2>/dev/null || \
            echo "declare -a CERT_SUCCESS_ROOTS=()"
        declare -p CERT_EXISTING_ROOTS 2>/dev/null || \
            echo "declare -a CERT_EXISTING_ROOTS=()"
        declare -p CERT_FAILED_ROOTS   2>/dev/null || \
            echo "declare -a CERT_FAILED_ROOTS=()"
        declare -p FAILED_CF_ACCOUNTS  2>/dev/null || \
            echo "declare -a FAILED_CF_ACCOUNTS=()"
    } > "$CF_CERT_STATUS_FILE"

    chmod 600 "$CF_CERT_STATUS_FILE"
}

# ── 加载证书请求状态 ─────────────────────────────────────────
load_cert_request_status() {
    CERT_SUCCESS_ROOTS=()
    CERT_EXISTING_ROOTS=()
    CERT_FAILED_ROOTS=()
    FAILED_CF_ACCOUNTS=()

    [[ -f "$CF_CERT_STATUS_FILE" ]] || return 1
    # shellcheck source=/dev/null
    source "$CF_CERT_STATUS_FILE"
    return 0
}

# ── 汇总展示证书请求结果 ─────────────────────────────────────
show_cert_request_summary() {
    echo ""
    log_info "证书处理结果："

    if [[ ${#CERT_SUCCESS_ROOTS[@]} -gt 0 ]]; then
        echo "  本次申请成功："
        for root_domain in "${CERT_SUCCESS_ROOTS[@]}"; do
            echo "    *.${root_domain}"
        done
    fi

    if [[ ${#CERT_EXISTING_ROOTS[@]} -gt 0 ]]; then
        echo "  已存在并跳过："
        for root_domain in "${CERT_EXISTING_ROOTS[@]}"; do
            echo "    *.${root_domain}"
        done
    fi

    if [[ ${#CERT_FAILED_ROOTS[@]} -gt 0 ]]; then
        echo "  申请失败："
        for root_domain in "${CERT_FAILED_ROOTS[@]}"; do
            echo "    *.${root_domain}"
        done
    fi

    if [[ ${#FAILED_CF_ACCOUNTS[@]} -gt 0 ]]; then
        local -A seen_failed_accounts=()
        echo "  需要检查的 CF 账号："
        for cf_idx in "${FAILED_CF_ACCOUNTS[@]}"; do
            [[ -n "${seen_failed_accounts[$cf_idx]:-}" ]] && continue
            seen_failed_accounts["$cf_idx"]=1
            echo "    账号 ${cf_idx}"
        done
    fi
}

# ── 重建 CF_INI_FILES 数组 ───────────────────────────────────
rebuild_cf_ini_files() {
    CF_INI_FILES=()
    for i in $(seq 1 "${CF_ACCOUNT_COUNT:-1}"); do
        CF_INI_FILES+=("${CF_CONFIG_DIR}/cf_account_${i}.ini")
    done
}

# ── 重新配置指定 CF 账号 ─────────────────────────────────────
reconfigure_cf_accounts() {
    local account_indexes=("$@")

    mkdir -p "$CF_CONFIG_DIR"
    chmod 700 "$CF_CONFIG_DIR"

    for i in "${account_indexes[@]}"; do
        echo ""
        log_info "── 配置第 ${i} 个 CF 账号 ──"
        read -rp "  账号 ${i} 的 CF API Token: " cf_token

        local ini_file="${CF_CONFIG_DIR}/cf_account_${i}.ini"
        cat > "$ini_file" << INI
# Cloudflare API Token - 账号 ${i}
dns_cloudflare_api_token = ${cf_token}
INI
        chmod 600 "$ini_file"
        log_info "账号 ${i} 配置已保存: $ini_file"
    done

    rebuild_cf_ini_files
}

# ── 配置 Cloudflare 账号 ─────────────────────────────────────
setup_cf_accounts() {
    echo ""
    log_step "配置 Cloudflare 账号"
    echo ""

    load_cert_request_status >/dev/null 2>&1 || true

    if ls "${CF_CONFIG_DIR}"/cf_account_*.ini &>/dev/null 2>&1; then
        CF_ACCOUNT_COUNT=$(ls "${CF_CONFIG_DIR}"/cf_account_*.ini \
            2>/dev/null | wc -l)
        rebuild_cf_ini_files

        log_info "发现已有 CF 账号配置："
        ls "${CF_CONFIG_DIR}"/cf_account_*.ini | while read -r f; do
            echo "  $f"
        done
        echo ""

        if [[ ${#FAILED_CF_ACCOUNTS[@]} -gt 0 ]]; then
            local -A seen_failed_accounts=()
            local failed_account_indexes=()

            for cf_idx in "${FAILED_CF_ACCOUNTS[@]}"; do
                [[ -n "${seen_failed_accounts[$cf_idx]:-}" ]] && continue
                seen_failed_accounts["$cf_idx"]=1
                failed_account_indexes+=("$cf_idx")
            done

            if [[ ${#failed_account_indexes[@]} -gt 0 ]]; then
                echo "上次失败涉及账号: ${failed_account_indexes[*]}"
                read -rp "是否只重新配置失败账号？[Y/n]: " reconf_failed
                if [[ "${reconf_failed,,}" != "n" ]]; then
                    reconfigure_cf_accounts "${failed_account_indexes[@]}"
                    log_info "其余 CF 账号配置保持不变"
                    return
                fi
            fi
        fi

        read -rp "是否重新配置全部 CF 账号？[y/N]: " reconf
        if [[ "${reconf,,}" != "y" ]]; then
            log_info "使用已有 ${CF_ACCOUNT_COUNT} 个CF账号配置"
            return
        fi
    fi

    read -rp "你有几个 Cloudflare 账号？[默认1]: " CF_ACCOUNT_COUNT
    CF_ACCOUNT_COUNT=${CF_ACCOUNT_COUNT:-1}

    rm -f "${CF_CONFIG_DIR}"/cf_account_*.ini 2>/dev/null || true
    # shellcheck disable=SC2046
    reconfigure_cf_accounts $(seq 1 "$CF_ACCOUNT_COUNT")
}

# ── 收集域名信息 ─────────────────────────────────────────────
collect_domains() {
    echo ""
    log_step "配置域名信息"
    echo ""

    if load_domain_config; then
        log_info "发现已有域名配置："
        [[ -n "$XHTTP_DOMAIN"   ]] && echo "  xhttp CDN:  $XHTTP_DOMAIN"
        [[ -n "$GRPC_DOMAIN"    ]] && echo "  gRPC  CDN:  $GRPC_DOMAIN"
        [[ -n "$REALITY_DOMAIN" ]] && echo "  Reality:    $REALITY_DOMAIN"
        [[ -n "$ANYTLS_DOMAIN"  ]] && echo "  AnyTLS:     $ANYTLS_DOMAIN"
        echo ""
        read -rp "是否直接复用已有域名配置？[Y/n]: " reuse_domains
        if [[ "${reuse_domains,,}" != "n" ]]; then
            normalize_domain_arrays
            log_info "复用已有域名配置"
            return
        fi
    fi

    ALL_DOMAINS=()
    CDN_DOMAINS=()
    DIRECT_DOMAINS=()
    XHTTP_DOMAIN=""
    GRPC_DOMAIN=""
    REALITY_DOMAIN=""
    ANYTLS_DOMAIN=""
    DOMAIN_CF_ACCOUNT_KEYS=()
    DOMAIN_CF_ACCOUNT_VALS=()

    choose_cf_account_for_domain() {
        local domain="$1"
        local cf_idx

        CHOSEN_CF_IDX="1"

        if [[ "${CF_ACCOUNT_COUNT:-1}" -le 1 ]]; then
            return
        fi

        echo ""
        echo "  为域名 ${domain} 选择 Cloudflare 账号："
        for j in $(seq 1 "$CF_ACCOUNT_COUNT"); do
            echo "    账号${j}: $(grep 'api_token' \
                "${CF_CONFIG_DIR}/cf_account_${j}.ini" | \
                awk '{print $3}' | cut -c1-12)..."
        done

        read -rp "  使用第几个 CF 账号？[1-${CF_ACCOUNT_COUNT}]: " cf_idx
        CHOSEN_CF_IDX="${cf_idx:-1}"
    }

    add_domain_with_usage() {
        local usage_key="$1"
        local prompt_text="$2"
        local domain

        echo ""
        read -rp "${prompt_text}" domain
        domain="${domain,,}"

        [[ -z "$domain" ]] && return

        choose_cf_account_for_domain "$domain"

        case "$usage_key" in
            xhttp)
                XHTTP_DOMAIN="$domain"
                CDN_DOMAINS+=("$domain")
                log_info "域名 $domain → xhttp-CDN"
                ;;
            grpc)
                GRPC_DOMAIN="$domain"
                CDN_DOMAINS+=("$domain")
                log_info "域名 $domain → gRPC-CDN"
                ;;
            reality)
                REALITY_DOMAIN="$domain"
                DIRECT_DOMAINS+=("$domain")
                log_info "域名 $domain → Reality"
                ;;
            anytls)
                ANYTLS_DOMAIN="$domain"
                DIRECT_DOMAINS+=("$domain")
                log_info "域名 $domain → AnyTLS"
                ;;
            *)
                log_warn "未知用途: ${usage_key}"
                return
                ;;
        esac

        DOMAIN_CF_ACCOUNT_KEYS+=("$domain")
        DOMAIN_CF_ACCOUNT_VALS+=("$CHOSEN_CF_IDX")
        ALL_DOMAINS+=("$domain")
    }

    echo "  域名用途说明："
    echo "    xhttp    - VLESS+XHTTP 经 CF CDN 中转（开启 CF 代理）"
    echo "    grpc     - VLESS+gRPC 经 CF CDN 中转（开启 CF 代理）"
    echo "    reality  - VLESS+Reality 直连伪装域名（关闭 CF 代理）"
    echo "    anytls   - Sing-Box AnyTLS 直连（关闭 CF 代理）"
    echo "  没有某一类域名时可直接留空跳过。"
    echo ""

    add_domain_with_usage "xhttp"   "请输入 xhttp 域名（没有可留空）: "
    add_domain_with_usage "grpc"    "请输入 grpc 域名（没有可留空）: "
    add_domain_with_usage "reality" "请输入 reality 域名（没有可留空）: "
    add_domain_with_usage "anytls"  "请输入 anytls 域名（没有可留空）: "

    echo ""
    log_info "域名配置汇总："
    [[ -n "$XHTTP_DOMAIN"   ]] && echo "  xhttp CDN:  $XHTTP_DOMAIN"
    [[ -n "$GRPC_DOMAIN"    ]] && echo "  gRPC  CDN:  $GRPC_DOMAIN"
    [[ -n "$REALITY_DOMAIN" ]] && echo "  Reality:    $REALITY_DOMAIN"
    [[ -n "$ANYTLS_DOMAIN"  ]] && echo "  AnyTLS:     $ANYTLS_DOMAIN"
    echo ""

    read -rp "确认以上配置？[Y/n]: " confirm
    if [[ "${confirm,,}" == "n" ]]; then
        log_warn "重新配置域名..."
        collect_domains
        return
    fi

    save_domain_config
}

# ── 获取域名对应CF账号索引 ───────────────────────────────────
get_domain_cf_idx() {
    local domain="$1"
    for i in "${!DOMAIN_CF_ACCOUNT_KEYS[@]}"; do
        if [[ "${DOMAIN_CF_ACCOUNT_KEYS[$i]}" == "$domain" ]]; then
            echo "${DOMAIN_CF_ACCOUNT_VALS[$i]}"
            return
        fi
    done
    echo "1"
}

# ── FIX Bug4: 将证书部署到统一目录，并修正权限 ──────────────
# 供 Xray / Nginx / Sing-Box 读取
deploy_cert_for_domain() {
    return 0
    local root_domain="$1"
    local src_dir="/etc/letsencrypt/live/${root_domain}"
    local dst_dir="${DEPLOY_CERT_DIR}/${root_domain}"

    [[ -d "$src_dir" ]] || return 1

    mkdir -p "$dst_dir"
    chmod 755 "$dst_dir"

    # 复制文件（不用软链，避免权限穿透问题）
    install -m 644 "${src_dir}/fullchain.pem" "${dst_dir}/fullchain.pem"
    install -m 644 "${src_dir}/chain.pem"     "${dst_dir}/chain.pem"     2>/dev/null || true
    install -m 640 "${src_dir}/privkey.pem"   "${dst_dir}/privkey.pem"

    # 让 xray / sing-box / nginx 都能读取私钥
    # xray 默认用户是 nobody，nginx 默认用户是 www-data
    chown root:nobody "${dst_dir}/privkey.pem" 2>/dev/null || \
        chown root:nogroup "${dst_dir}/privkey.pem" 2>/dev/null || true
    chmod 640 "${dst_dir}/privkey.pem"

    log_info "证书已部署到: ${dst_dir}"
    log_info "  fullchain.pem → 644"
    log_info "  privkey.pem   → 640 (root:nobody)"
}

# ── 检查已有证书 ─────────────────────────────────────────────
check_existing_certs() {
    log_step "检查已有证书..."

    CERT_EXISTING_ROOTS=()
    local all_exist=true
    local checked_roots=()   # FIX Bug3: 不带 :-，正确初始化

    if [[ ${#ALL_DOMAINS[@]} -eq 0 ]]; then
        log_warn "未找到有效域名配置，不能跳过证书申请"
        return 1
    fi

    for domain in "${ALL_DOMAINS[@]}"; do
        local root_domain
        root_domain=$(echo "$domain" | awk -F. '{print $(NF-1)"."$NF}')

        # 避免重复检查同一根域名
        local already=false
        for r in "${checked_roots[@]}"; do   # FIX Bug3: 去掉 :-
            [[ "$r" == "$root_domain" ]] && already=true && break
        done
        $already && continue
        checked_roots+=("$root_domain")

        if [[ -f "/etc/letsencrypt/live/${root_domain}/fullchain.pem" ]]; then
            local expiry
            expiry=$(openssl x509 \
                -enddate -noout \
                -in "/etc/letsencrypt/live/${root_domain}/fullchain.pem" \
                2>/dev/null | cut -d= -f2)
            log_info "证书已存在: *.${root_domain} (到期: ${expiry})"
            CERT_EXISTING_ROOTS+=("$root_domain")
        else
            log_warn "证书不存在: *.${root_domain}"
            all_exist=false
        fi
    done

    $all_exist && return 0 || return 1
}

# ── 申请证书 ─────────────────────────────────────────────────
request_certificates() {
    log_step "开始申请 SSL 证书..."

    CERT_SUCCESS_ROOTS=()
    CERT_EXISTING_ROOTS=()
    CERT_FAILED_ROOTS=()
    FAILED_CF_ACCOUNTS=()

    # FIX Bug2: 用全局关联数组，而非函数内局部 declare -A
    declare -gA ROOT_DOMAIN_DONE=()

    for domain in "${ALL_DOMAINS[@]}"; do
        local cf_idx
        cf_idx=$(get_domain_cf_idx "$domain")
        local ini_file="${CF_INI_FILES[$((cf_idx-1))]}"

        local root_domain
        root_domain=$(echo "$domain" | awk -F. '{print $(NF-1)"."$NF}')

        # 同根域名只申请一次
        if [[ -n "${ROOT_DOMAIN_DONE[$root_domain]:-}" ]]; then
            log_info "*.${root_domain} 已处理，跳过 $domain"
            continue
        fi

        # 已有证书则跳过
        if [[ -f "/etc/letsencrypt/live/${root_domain}/fullchain.pem" ]]; then
            log_info "证书已存在，跳过: *.${root_domain}"
            CERT_EXISTING_ROOTS+=("$root_domain")
            ROOT_DOMAIN_DONE["$root_domain"]="1"
            # FIX Bug4: 即使证书已存在也要确保部署目录是最新的
            continue
        fi

        log_info "申请证书: *.${root_domain} (CF账号${cf_idx})"
        log_info "使用配置: $ini_file"

        # FIX Bug1: 用进程替换代替管道，避免子 shell 吃掉变量写入
        local certbot_output certbot_rc
        if certbot_output=$(certbot certonly \
            --dns-cloudflare \
            --dns-cloudflare-credentials "$ini_file" \
            --dns-cloudflare-propagation-seconds 30 \
            -d "${root_domain}" \
            -d "*.${root_domain}" \
            --email "admin@${root_domain}" \
            --agree-tos \
            --non-interactive \
            --expand 2>&1); then
            certbot_rc=0
        else
            certbot_rc=$?
        fi

        # 把输出打印出来（缩进美化）
        while IFS= read -r line; do
            echo "  $line"
        done <<< "$certbot_output"

        if [[ $certbot_rc -eq 0 && -f "/etc/letsencrypt/live/${root_domain}/fullchain.pem" ]]; then
            log_info "证书申请成功: *.${root_domain}"
            CERT_SUCCESS_ROOTS+=("$root_domain")
            ROOT_DOMAIN_DONE["$root_domain"]="1"
            # FIX Bug4: 申请成功后立即部署到统一目录并修正权限
            deploy_cert_for_domain "$root_domain"
        else
            log_error "证书申请失败: ${root_domain}"
            log_warn "certbot 退出码: ${certbot_rc}"
            CERT_FAILED_ROOTS+=("$root_domain")
            FAILED_CF_ACCOUNTS+=("$cf_idx")
            log_warn "请检查："
            echo "  1. 域名是否在该CF账号下"
            echo "  2. API Token 是否有 Zone:DNS:Edit 权限"
            echo "  3. 域名是否已添加到CF"
            echo "  4. 上面 certbot 输出中的具体报错"
        fi
    done

    save_cert_request_status
    show_cert_request_summary
}

# ── 配置自动续期 ─────────────────────────────────────────────
setup_auto_renew() {
    log_step "配置证书自动续期..."

    mkdir -p /etc/letsencrypt/renewal-hooks/deploy

    # FIX Bug4: hook 同时重新部署证书并重载所有服务
    cat > /etc/letsencrypt/renewal-hooks/deploy/xray-nginx-deploy-reload.sh << HOOK
#!/bin/bash
# renew hook: reload services to pick up updated LetsEncrypt certs
systemctl reload  nginx    2>/dev/null && echo "nginx reloaded"    || true
systemctl restart xray     2>/dev/null && echo "xray restarted"    || true
systemctl restart sing-box 2>/dev/null && echo "sing-box restarted" || true
HOOK
    chmod +x /etc/letsencrypt/renewal-hooks/deploy/xray-nginx-deploy-reload.sh

    if certbot_uses_snap; then
        crontab -l 2>/dev/null | grep -v certbot | crontab - || true
        log_info "自动续期配置完成（使用 Snap 自带 timer）"
        log_info "可用 systemctl list-timers | grep certbot 查看续期计划"
    else
        (crontab -l 2>/dev/null | grep -v certbot; \
         echo "0 3 * * * certbot renew --quiet") | crontab -
        log_info "自动续期配置完成（每天凌晨3点检查）"
    fi
}

# ── 模块入口 ─────────────────────────────────────────────────
run_cert() {
    log_step "========== SSL 证书申请 =========="

    # 1. 安装 certbot
    install_certbot

    # 2. 配置 CF 账号（先设账号再填域名）
    setup_cf_accounts

    # 3. 收集域名信息
    collect_domains

    # 4. 检查已有证书，有则跳过申请
    if check_existing_certs; then
        log_info "所有域名证书已存在，跳过申请"
        CERT_SUCCESS_ROOTS=()
        CERT_FAILED_ROOTS=()
        FAILED_CF_ACCOUNTS=()
        save_cert_request_status
        show_cert_request_summary

        # FIX Bug4: 即使跳过申请，也要确保证书已部署到统一目录
        declare -A _seen_deploy=()
        local _root
        for domain in "${ALL_DOMAINS[@]}"; do
            _root=$(echo "$domain" | awk -F. '{print $(NF-1)"."$NF}')
            [[ -n "${_seen_deploy[$_root]:-}" ]] && continue
            _seen_deploy["$_root"]=1
            deploy_cert_for_domain "$_root"
        done
    else
        request_certificates
    fi

    # 5. 配置自动续期
    setup_auto_renew

    log_info "========== SSL 证书模块完成 =========="
    echo ""
    log_info "Cert path (use Let's Encrypt default directory):"
    echo "  fullchain: /etc/letsencrypt/live/<root-domain>/fullchain.pem"
    echo "  privkey:   /etc/letsencrypt/live/<root-domain>/privkey.pem"
}
